=== eristocrates/ipa/Source-code/Host-environment/Common-Language-Runtime/FSharp/Interactive/ServiceDesk/SolarWinds/incident.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "data": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "select": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "name": {
                "type": "string",
                "minLength": 1
              },
              "number": {
                "type": "number"
              },
              "hidden": {}
            },
            "required": [
              "type",
              "name",
              "number"
            ]
          },
          "requester": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string",
                "minLength": 1
              },
              "avatar": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "minLength": 1
                  },
                  "initials": {
                    "type": "string",
                    "minLength": 1
                  },
                  "color": {
                    "type": "string",
                    "minLength": 1
                  },
                  "klass": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "type",
                  "initials",
                  "color",
                  "klass"
                ]
              }
            },
            "required": [
              "type",
              "id",
              "name",
              "avatar"
            ]
          },
          "title": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "minLength": 1
              },
              "link": {
                "type": "string",
                "minLength": 1
              },
              "augmented": {
                "type": "boolean"
              },
              "external": {
                "type": "boolean"
              }
            },
            "required": [
              "type",
              "value",
              "link",
              "augmented",
              "external"
            ]
          },
          "state": {
            "type": "object",
            "properties": {
              "color_set": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "minLength": 1
              },
              "type": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "color_set",
              "value",
              "type"
            ]
          },
          "sub_type": {},
          "type": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "type",
              "value"
            ]
          },
          "site": {},
          "department": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "type",
              "value"
            ]
          },
          "assigned_to": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string",
                "minLength": 1
              },
              "avatar": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "minLength": 1
                  },
                  "initials": {
                    "type": "string",
                    "minLength": 1
                  },
                  "color": {
                    "type": "string",
                    "minLength": 1
                  },
                  "klass": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "type",
                  "initials",
                  "color",
                  "klass"
                ]
              }
            },
            "required": [
              "type",
              "id",
              "name",
              "avatar"
            ]
          },
          "priority": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "minLength": 1
              },
              "translate": {
                "type": "boolean"
              }
            },
            "required": [
              "type",
              "value",
              "translate"
            ]
          },
          "created_at": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "type",
              "value"
            ]
          },
          "created_by": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string",
                "minLength": 1
              },
              "avatar": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "minLength": 1
                  },
                  "initials": {
                    "type": "string",
                    "minLength": 1
                  },
                  "color": {
                    "type": "string",
                    "minLength": 1
                  },
                  "klass": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "type",
                  "initials",
                  "color",
                  "klass"
                ]
              }
            },
            "required": [
              "type",
              "id",
              "name",
              "avatar"
            ]
          },
          "tag_list": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "type",
              "value"
            ]
          },
          "number": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "value": {
                "type": "number"
              }
            },
            "required": [
              "type",
              "value"
            ]
          },
          "slm": {},
          "preview": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "type"
            ]
          }
        }
      }
    },
    "pagination": {
      "type": "object",
      "properties": {
        "perPage": {
          "type": "number"
        },
        "offset": {
          "type": "number"
        },
        "currentPage": {
          "type": "number"
        }
      },
      "required": [
        "perPage",
        "offset",
        "currentPage"
      ]
    },
    "count": {
      "type": "number"
    },
    "related": {},
    "is_empty_db": {
      "type": "boolean"
    }
  },
  "required": [
    "data",
    "pagination",
    "count",
    "is_empty_db"
  ]
}

=== eristocrates/ipa/Source-code/Host-environment/Common-Language-Runtime/FSharp/Interactive/ServiceDesk/SolarWinds/incident.json
{
  "data": [
    {
      "id": 188911185,
      "select": {
        "type": "select",
        "name": "Unable to access the original GIS Land Information map",
        "number": 88487,
        "hidden": null
      },
      "requester": {
        "type": "user",
        "id": 6299152,
        "name": "Charlene Green",
        "avatar": {
          "type": "initials",
          "initials": "CG",
          "color": "var(--colors-foreground-7-100)",
          "klass": "User"
        }
      },
      "title": {
        "type": "link",
        "value": "Unable to access the original GIS Land Information map",
        "link": "/incidents/188911185-unable-to-access-the-original-gis-land-information-map",
        "augmented": true,
        "external": false
      },
      "state": {
        "color_set": "5",
        "value": "Closed",
        "type": "pill"
      },
      "sub_type": null,
      "type": {
        "type": "text",
        "value": "GIS Support"
      },
      "site": null,
      "department": {
        "type": "text",
        "value": "LCG - Operations"
      },
      "assigned_to": {
        "type": "user",
        "id": 6249860,
        "name": "Tricia McClenahan",
        "avatar": {
          "type": "initials",
          "initials": "TM",
          "color": "var(--colors-foreground-7-500)",
          "klass": "User"
        }
      },
      "priority": {
        "type": "text",
        "value": "Medium",
        "translate": true
      },
      "created_at": {
        "type": "text",
        "value": "Aug 06, 2026"
      },
      "created_by": {
        "type": "user",
        "id": 9894151,
        "name": "Brandon Collier",
        "avatar": {
          "type": "initials",
          "initials": "BC",
          "color": "var(--colors-foreground-7-800)",
          "klass": "User"
        }
      },
      "tag_list": {
        "type": "text",
        "value": "LCG - Operations"
      },
      "number": {
        "type": "text",
        "value": 88487
      },
      "slm": null,
      "preview": {
        "type": "eagle_eye"
      }
    }
  ],
  "pagination": {
    "perPage": 100,
    "offset": 0,
    "currentPage": 1
  },
  "count": 1,
  "related": null,
  "is_empty_db": false
}
